"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'true', '1', 'yes', 'on'}


def env_list(name, default=''):
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


# Never ship a development key or silently enable Django debug output.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set in the environment.')

DEBUG = env_bool('DJANGO_DEBUG', False)
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,::1')
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:8443,http://127.0.0.1:8443,http://localhost:5173,http://127.0.0.1:5173' if DEBUG else '',
)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'store.middleware.ApiCorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {'charset': 'utf8mb4', 'connect_timeout': 10},
    }
}


# Reuse healthy database connections across requests, but periodically recycle them.
DATABASES['default']['CONN_MAX_AGE'] = int(os.getenv('DB_CONN_MAX_AGE', '60'))
DATABASES['default']['CONN_HEALTH_CHECKS'] = True
if os.getenv('DB_SSL_CA', '').strip():
    DATABASES['default']['OPTIONS'] = {'ssl': {'ca': os.getenv('DB_SSL_CA').strip()}}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))).resolve()
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '').strip()
RAZORPAY_SECRET = os.getenv('RAZORPAY_SECRET', '').strip()

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com').strip()
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').strip().lower() in {'true', '1', 'yes'}
EMAIL_HOST_USER = os.getenv('EMAIL', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('PASSWORD', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER).strip()

# Production must sit behind HTTPS. When TLS is terminated by a trusted reverse
# proxy, set SECURE_PROXY_SSL_HEADER_ENABLED=True in that deployment environment.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
if env_bool('SECURE_PROXY_SSL_HEADER_ENABLED', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    production_required = {
        'ALLOWED_HOSTS': os.getenv('ALLOWED_HOSTS', '').strip(),
        'CORS_ALLOWED_ORIGINS': os.getenv('CORS_ALLOWED_ORIGINS', '').strip(),
        'EMAIL': EMAIL_HOST_USER,
        'PASSWORD': EMAIL_HOST_PASSWORD,
        'RAZORPAY_KEY_ID': RAZORPAY_KEY_ID,
        'RAZORPAY_SECRET': RAZORPAY_SECRET,
        'CSRF_TRUSTED_ORIGINS': ','.join(CSRF_TRUSTED_ORIGINS),
        'DB_NAME': os.getenv('DB_NAME', '').strip(),
        'DB_USER': os.getenv('DB_USER', '').strip(),
        'DB_PASSWORD': os.getenv('DB_PASSWORD', '').strip(),
        'DB_HOST': os.getenv('DB_HOST', '').strip(),
        'DB_PORT': os.getenv('DB_PORT', '').strip(),
    }
    missing_settings = [name for name, value in production_required.items() if not value]
    if missing_settings:
        raise ImproperlyConfigured('Missing production settings: ' + ', '.join(missing_settings))
    if not RAZORPAY_KEY_ID.startswith('rzp_live_'):
        raise ImproperlyConfigured('Production must use a live Razorpay key ID.')
    if len(SECRET_KEY) < 50 or 'generate-a-unique-secret' in SECRET_KEY.lower():
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY to a unique random value of at least 50 characters.')
    if '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured('ALLOWED_HOSTS must list the production hostnames explicitly.')
    if any(host.startswith(('http://', 'https://')) for host in ALLOWED_HOSTS):
        raise ImproperlyConfigured('ALLOWED_HOSTS must contain hostnames without a scheme.')
    if any(not origin.startswith('https://') for origin in CORS_ALLOWED_ORIGINS):
        raise ImproperlyConfigured('Production CORS_ALLOWED_ORIGINS must use HTTPS origins.')
    if any(not origin.startswith('https://') for origin in CSRF_TRUSTED_ORIGINS):
        raise ImproperlyConfigured('Production CSRF_TRUSTED_ORIGINS must use HTTPS origins.')
    if any('example.com' in origin.lower() for origin in CORS_ALLOWED_ORIGINS + CSRF_TRUSTED_ORIGINS):
        raise ImproperlyConfigured('Replace example.com with your production website and API domains.')
    if not SECURE_SSL_REDIRECT or not SESSION_COOKIE_SECURE or not CSRF_COOKIE_SECURE or SECURE_HSTS_SECONDS < 1:
        raise ImproperlyConfigured('Production requires HTTPS redirects, secure cookies, and HSTS.')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/hour',
        'user': '1000/hour',
        'signup_otp': '5/hour',
        'signup': '10/hour',
        'login': '10/minute',
    },
}
