from django.urls import path

from .views import (
    address_detail,
    address_list,
    admin_product_detail,
    admin_product_list,
    admin_summary,
    admin_order_list,
    admin_order_status_update,
    admin_customer_list,
    admin_support_tickets,
    admin_support_ticket_update,
    admin_analytics,
    admin_notifications,
    change_password,
    category_list,
    product_filters,
    login,
    logout,
    me,
    newsletter_subscribe,
    order_list,
    create_payment_order,
    create_cod_order,
    verify_payment,
    support_ticket_create,
    cart_list,
    cart_item_detail,
    wishlist_list,
    wishlist_detail,
    product_detail,
    product_list,
    signup,
    send_signup_otp,
)

urlpatterns = [
    path('categories/', category_list, name='category-list'),
    path('products/filters/', product_filters, name='product-filters'),
    path('products/', product_list, name='product-list'),
    path('products/<slug:slug>/', product_detail, name='product-detail'),
    path('admin/products/', admin_product_list, name='admin-product-list'),
    path('admin/products/<int:product_id>/', admin_product_detail, name='admin-product-detail'),
    path('admin/summary/', admin_summary, name='admin-summary'),
    path('admin/orders/', admin_order_list, name='admin-order-list'),
    path('admin/orders/<int:order_id>/', admin_order_status_update, name='admin-order-status-update'),
    path('admin/customers/', admin_customer_list, name='admin-customer-list'),
    path('admin/support/', admin_support_tickets, name='admin-support-tickets'),
    path('admin/support/<int:ticket_id>/', admin_support_ticket_update, name='admin-support-ticket-update'),
    path('admin/analytics/', admin_analytics, name='admin-analytics'),
    path('admin/notifications/', admin_notifications, name='admin-notifications'),
    path('newsletter/subscribe/', newsletter_subscribe, name='newsletter-subscribe'),
    path('auth/signup/', signup, name='auth-signup'),
    path('auth/signup/send-otp/', send_signup_otp, name='auth-signup-send-otp'),
    path('auth/login/', login, name='auth-login'),
    path('auth/logout/', logout, name='auth-logout'),
    path('auth/me/', me, name='auth-me'),
    path('auth/change-password/', change_password, name='auth-change-password'),
    path('orders/', order_list, name='order-list'),
    path('cart/', cart_list, name='cart-list'),
    path('cart/<int:item_id>/', cart_item_detail, name='cart-item-detail'),
    path('wishlist/', wishlist_list, name='wishlist-list'),
    path('wishlist/<int:product_id>/', wishlist_detail, name='wishlist-detail'),
    path('payments/create-order/', create_payment_order, name='payment-create-order'),
    path('payments/verify/', verify_payment, name='payment-verify'),
    path('orders/cash-on-delivery/', create_cod_order, name='order-cash-on-delivery'),
    path('addresses/', address_list, name='address-list'),
    path('addresses/<int:address_id>/', address_detail, name='address-detail'),
    path('support/tickets/', support_ticket_create, name='support-ticket-create'),
]
