# Generated by Django 5.2.17 on 2026-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_fix_tshirt_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLaunchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='can_launch_site',
            field=models.BooleanField(default=False),
        ),
    ]
